// Exports ABIs from contracts/out into app/src/abi/generated.ts and scripts/src/abi.ts (as const, for viem typing).
// Run after `forge build`:  node scripts/export-abis.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const contracts = [
  "CreditAccountFactory",
  "CreditAccount",
  "RiskEngine",
  "LenderPool",
  "OracleAdapter",
  "MarketClock",
  "SoftLiquidator",
  "HardLiquidator",
  "AutoRepay",
  "DexAdapter",
  "FeeCollector",
  "ProjectTokenHooks",
  "ComplianceRegistry",
  "HoldcreditTimelock",
];

let out = "// AUTO-GENERATED by scripts/export-abis.mjs - do not edit.\n\n";
for (const name of contracts) {
  const art = JSON.parse(readFileSync(join(root, "contracts", "out", `${name}.sol`, `${name}.json`), "utf8"));
  out += `export const ${name[0].toLowerCase()}${name.slice(1)}Abi = ${JSON.stringify(art.abi)} as const;\n\n`;
}
out += `export const erc20Abi = [
  {"type":"function","name":"balanceOf","stateMutability":"view","inputs":[{"name":"a","type":"address"}],"outputs":[{"type":"uint256"}]},
  {"type":"function","name":"allowance","stateMutability":"view","inputs":[{"name":"o","type":"address"},{"name":"s","type":"address"}],"outputs":[{"type":"uint256"}]},
  {"type":"function","name":"approve","stateMutability":"nonpayable","inputs":[{"name":"s","type":"address"},{"name":"v","type":"uint256"}],"outputs":[{"type":"bool"}]},
  {"type":"function","name":"decimals","stateMutability":"view","inputs":[],"outputs":[{"type":"uint8"}]},
  {"type":"function","name":"symbol","stateMutability":"view","inputs":[],"outputs":[{"type":"string"}]}
] as const;
`;

for (const target of [join(root, "app", "src", "abi", "generated.ts"), join(root, "scripts", "src", "abi.ts")]) {
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, out);
  console.log("wrote", target);
}
